create or replace function create_subject_if_not_exists(_name text, _semester_type text, _year text) returns void as
$$
begin

    if not exists(select id from public.subject where name = _name) then
        insert into public.subject(name, semester_type_id, year_id)
        values (_name, find_semester_type_id_by_name(_semester_type), find_year_id_by_name(_year));
    end if;

end;

$$ language plpgsql;

select create_subject_if_not_exists('Бизнис и менаџмент', 'Зимски', 'Прва'),
       create_subject_if_not_exists('Вовед во компјутерските науки', 'Зимски', 'Прва'),
       create_subject_if_not_exists('Професионални вештини', 'Зимски', 'Прва'),
       create_subject_if_not_exists('Структурно програмирање', 'Зимски', 'Прва'),
       create_subject_if_not_exists('Педагогија', 'Зимски', 'Прва'),
       create_subject_if_not_exists('Дискретни структури', 'Зимски', 'Прва'),
       create_subject_if_not_exists('Калкулус', 'Зимски', 'Прва'),
       create_subject_if_not_exists('Калкулус 1', 'Зимски', 'Прва'),
       create_subject_if_not_exists('Дизајн на дигитални кола', 'Зимски', 'Прва'),
       create_subject_if_not_exists('Физика', 'Зимски', 'Прва'),
       create_subject_if_not_exists('Дискретна математика', 'Летен', 'Прва'),
       create_subject_if_not_exists('Компјутерски архитектури', 'Летен', 'Прва'),
       create_subject_if_not_exists('Објектно-ориентирано програмирање', 'Летен', 'Прва'),
       create_subject_if_not_exists('Основи на сајбер безбедноста', 'Летен', 'Прва'),
       create_subject_if_not_exists('Спорт и здравје', 'Летен', 'Прва'),
       create_subject_if_not_exists('Бизнис статистика', 'Летен', 'Прва'),
       create_subject_if_not_exists('Калкулус 2', 'Летен', 'Прва'),
       create_subject_if_not_exists('Компјутерски компоненти', 'Летен', 'Прва'),
       create_subject_if_not_exists('Креативни вештини за решавање проблеми', 'Летен', 'Прва'),
       create_subject_if_not_exists('Маркетинг', 'Летен', 'Прва'),
       create_subject_if_not_exists('Објектно ориентирана анализа и дизајн', 'Летен', 'Прва'),
       create_subject_if_not_exists('Основи на веб дизајн', 'Летен', 'Прва'),
       create_subject_if_not_exists('ИТ системи за учење', 'Летен', 'Прва'),
       create_subject_if_not_exists('Архитектура и организација на компјутери', 'Летен', 'Прва'),
       create_subject_if_not_exists('Дискретни структури 2', 'Летен', 'Прва'),
       create_subject_if_not_exists('Алгоритми и податочни структури', 'Зимски', 'Втора'),
       create_subject_if_not_exists('Компјутерски мрежи', 'Зимски', 'Втора'),
       create_subject_if_not_exists('Основи на теоријата на информации', 'Зимски', 'Втора'),
       create_subject_if_not_exists('Инженерска математика', 'Зимски', 'Втора'),
       create_subject_if_not_exists('Интернет програмирање на клиентска страна', 'Зимски', 'Втора'),
       create_subject_if_not_exists('Напредно програмирање', 'Зимски', 'Втора'),
       create_subject_if_not_exists('Основи на комуникациски системи', 'Зимски', 'Втора'),
       create_subject_if_not_exists('Управување со техничката поддршка', 'Зимски', 'Втора'),
       create_subject_if_not_exists('Компјутерски мрежи и безбедност', 'Зимски', 'Втора'),
       create_subject_if_not_exists('Мултимедијални технологии', 'Зимски', 'Втора'),
       create_subject_if_not_exists('Веројатност и статистика', 'Зимски', 'Втора'),
       create_subject_if_not_exists('Дигитизација', 'Зимски', 'Втора'),
       create_subject_if_not_exists('Шаблони за дизајн на кориснички', 'Зимски', 'Втора'),
       create_subject_if_not_exists('Економија за ИКТ инженери', 'Зимски', 'Втора'),
       create_subject_if_not_exists('Безжични и мобилни системи', 'Летен', 'Втора'),
       create_subject_if_not_exists('Оперативни системи', 'Летен', 'Втора'),
       create_subject_if_not_exists('Вештачка интелигенција', 'Летен', 'Втора'),
       create_subject_if_not_exists('Визуелно програмирање', 'Летен', 'Втора'),
       create_subject_if_not_exists('Вовед во екоинформатиката', 'Летен', 'Втора'),
       create_subject_if_not_exists('Вовед во случајни процеси', 'Летен', 'Втора'),
       create_subject_if_not_exists('Интернет технологии', 'Летен', 'Втора'),
       create_subject_if_not_exists('Медиуми и комуникации', 'Летен', 'Втора'),
       create_subject_if_not_exists('Одржливи и енергетски ефикасни компјутерски системи', 'Летен', 'Втора'),
       create_subject_if_not_exists('Софтверско инженерство', 'Летен', 'Втора'),
       create_subject_if_not_exists('ИКТ во образованието', 'Летен', 'Втора'),
       create_subject_if_not_exists('Дизајн на алгоритми', 'Летен', 'Втора'),
       create_subject_if_not_exists('Е-влада', 'Летен', 'Втора'),
       create_subject_if_not_exists('Електрични кола', 'Летен', 'Втора'),
       create_subject_if_not_exists('Компјутерска графика', 'Летен', 'Втора'),
       create_subject_if_not_exists('Споделување и пресметување во толпа', 'Летен', 'Втора'),
       create_subject_if_not_exists('Анализа на софтверските барања', 'Летен', 'Втора'),
       create_subject_if_not_exists('Дигитално процесирање на слика', 'Летен', 'Втора'),
       create_subject_if_not_exists('Теорија на информации со дигитални комуникации', 'Летен', 'Втора'),
       create_subject_if_not_exists('Концепти на информатичко општество', 'Летен', 'Втора'),
       create_subject_if_not_exists('Администрација на системи', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Бази на податоци,зимски', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Мрежна безбедност', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Веб програмирање', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Визуелизација', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Вовед во науката за податоци', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Информациска безбедност', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Компјутерска етика', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Компјутерски звук говор и музика', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Линеарна алгебра и примени', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Мултимедиски мрежи', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Основи на роботиката', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Паралелно и дистрибуирано процесирање', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Дизајн на образовен софтвер', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Напреден веб дизајн', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Линеарна алгебра и примени', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Паралелно и дистрибуирано процесирање', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Дизајн и архитектура на софтвер', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Информациска безбедност', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Компјутерска електроника', 'Зимски', 'Трета'),
       create_subject_if_not_exists('Администрација на мрежи', 'Летен', 'Трета'),
       create_subject_if_not_exists('Виртуелизација', 'Летен', 'Трета'),
       create_subject_if_not_exists('Агентно-базирани системи', 'Летен', 'Трета'),
       create_subject_if_not_exists('Безжични мултимедиски системи', 'Летен', 'Трета'),
       create_subject_if_not_exists('Вградливи микропроцесорски системи', 'Летен', 'Трета'),
       create_subject_if_not_exists('Вовед во мрежна наука', 'Летен', 'Трета'),
       create_subject_if_not_exists('Дигитална форензика', 'Летен', 'Трета'),
       create_subject_if_not_exists('Дизајн на интеракцијата човек-компјутер', 'Летен', 'Трета'),
       create_subject_if_not_exists('Електронска и мобилна трговија', 'Летен', 'Трета'),
       create_subject_if_not_exists('Инфраструктурно програмирање', 'Летен', 'Трета'),
       create_subject_if_not_exists('Континуирана интеграција и испорака', 'Летен', 'Трета'),
       create_subject_if_not_exists('Криптографија', 'Летен', 'Трета'),
       create_subject_if_not_exists('Мерење и анализа на интернет сообраќај', 'Летен', 'Трета'),
       create_subject_if_not_exists('Мултимедиски системи', 'Летен', 'Трета'),
       create_subject_if_not_exists('Сервисно ориентирани архитектури', 'Летен', 'Трета'),
       create_subject_if_not_exists('Софтверски дефинирана безбедност', 'Летен', 'Трета'),
       create_subject_if_not_exists('Персонализирано учење', 'Летен', 'Трета'),
       create_subject_if_not_exists('Психологија на училишна возраст', 'Летен', 'Трета'),
       create_subject_if_not_exists('Работа со надарени ученици', 'Летен', 'Трета'),
       create_subject_if_not_exists('Дигитални библиотеки', 'Летен', 'Трета'),
       create_subject_if_not_exists('Софтверски квалитет и тестирање', 'Летен', 'Трета'),
       create_subject_if_not_exists('Учење на далечина', 'Летен', 'Трета'),
       create_subject_if_not_exists('Дизајн на интеракцијата човек-компјутер', 'Летен', 'Трета'),
       create_subject_if_not_exists('Машинско учење', 'Летен', 'Трета'),
       create_subject_if_not_exists('Формални јазици и автомати', 'Летен', 'Трета'),
       create_subject_if_not_exists('Географски информациски системи', 'Летен', 'Трета'),
       create_subject_if_not_exists('Интегрирани системи', 'Летен', 'Трета'),
       create_subject_if_not_exists('Паралелно програмирање', 'Летен', 'Трета'),
       create_subject_if_not_exists('Податочно рударство', 'Летен', 'Трета'),
       create_subject_if_not_exists('Процесирање на сигналите', 'Летен', 'Трета'),
       create_subject_if_not_exists('Процесна роботика', 'Летен', 'Трета'),
       create_subject_if_not_exists('Современи компјутерски архитектури', 'Летен', 'Трета'),
       create_subject_if_not_exists('Статистичко моделирање', 'Летен', 'Трета'),
       create_subject_if_not_exists('Процесирање на сигналите', 'Летен', 'Трета'),
       create_subject_if_not_exists('Електронска и мобилна трговија', 'Летен', 'Трета'),
       create_subject_if_not_exists('Интегрирани системи', 'Летен', 'Трета'),
       create_subject_if_not_exists('Формални јазици и автомати', 'Летен', 'Трета'),
       create_subject_if_not_exists('Дистрибуирани системи', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Пресметување во облак', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Администрација на бази на податоци', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Анализа и дизајн на ИС', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Веб базирани системи', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Вовед во биоинформатиката', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Вовед во паметни градови', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Дигитална постпродукција', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Дистрибуирано складирање на податоци', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Имплементација на системи со слободен и отворен код', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Иновации во ИКТ', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Машинска визија', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Методологија на истражувањето во ИКТ', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Мобилни информациски системи', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Мобилни платформи и програмирање', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Мрежна и мобилна форензика', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Оптички мрежи', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Софтверски дефинирани мрежи', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Интернет на нештата', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Напредна интеракција човек компјутер', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Програмирање на видео игри', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Социјални мрежи и медиуми', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Програмски парадигми', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Автономна роботика', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Вовед во анализа на временските серии', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Вовед во препознавање на облици', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Менаџмент информациски системи', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Моделирање и симулација', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Обработка на природните јазици', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Операциони истражувања', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Рударење на масивни податоци', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Системи за поддршка при одлучувањето', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Софтвер за вградливи системи', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Компјутерски поддржано производство', 'Зимски', 'Четврта'),
       create_subject_if_not_exists('Блоковски вериги и криптовалути', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Веб пребарувачки системи', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Географски информациски системи', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Етичко хакирање', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Интелигентни системи', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Мобилни апликации', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Моделирање и менаџирање на бизнис процеси', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Модерни трендови во роботика', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Напредни бази на податоци', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Напредни теми од криптографија', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Неструктурирани бази на податоци', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Претприемништво', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Складови на податоци и аналитичка обработка', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Споделување и пресметување во толпа', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Управување со ИКТ проекти', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Дизајн на компјутерски мрежи', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Македонски јазик', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Методика на информатиката', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Виртуелна реалност', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Вовед во когнитивни науки', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Компјутерска анимација', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Биолошки инспирирано пресметување', 'Летен', 'Четврта'),
       create_subject_if_not_exists('ИКТ за развој', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Интелигентни информациски системи', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Пресметковна биологија', 'Летен', 'Четврта'),
       create_subject_if_not_exists('Програмски јазици и компајлери', 'Летен', 'Четврта');


