create table if not exists public.subject
(
    "id"               bigserial not null,
    "name"             text,
    "semester_type_id" bigint,
    "year_id"          bigint,
    primary key ("id"),
    unique ("name")
);
alter table public.subject
    owner to postgres;

create table if not exists public.year
(
    id   bigint generated by default as identity
        constraint year_pkey
            primary key,
    name varchar(255)
);
alter table public.year
    owner to postgres;

create table if not exists public.semester_type
(
    id   bigint generated by default as identity
        constraint semester_type_pkey
            primary key,
    name varchar(255)
);
alter table if exists public.semester_type
    owner to postgres;

create table if not exists public.exam_type
(
    id   bigint generated by default as identity
        constraint exam_type_pkey
            primary key,
    name varchar(255)
);
alter table public.exam_type
    owner to postgres;

create table if not exists auth_user.users
(
    id           bigserial
        primary key,
    date_created date,
    email        varchar(255) unique,
    name         varchar(255),
    password     varchar(255),
    surname      varchar(255),
    username     varchar(255)
);
alter table auth_user.users
    owner to postgres;

create table if not exists auth_user.roles
(
    id   bigserial
        primary key,
    name varchar(255)
);
alter table auth_user.roles
    owner to postgres;

create table if not exists auth_user.user_roles
(
    id      bigserial
        primary key,
    role_id bigint
        constraint fkrhfovtciq1l558cw6udg0h0d3
            references auth_user.roles,
    user_id bigint
        constraint fkhfh9dx7w3ubf1co1vdev94g3f
            references auth_user.users
);
alter table auth_user.user_roles
    owner to postgres;

